CCS_Sample: "P5-A1"
REF_Sample: "P5-A1"
software_Path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/scripts/software
sampRunscripts_Path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/scripts/sample_phasing
SNV_path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/data
bam_path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/data
refFasta_path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/data
OUT_path: /home/liuhj/Documents/projects/liuhj/scripts-phasing/phasing-2023.09/results-test
iSNVminFreq: 0.1
iSNVmaxFreq: 0.9
show_topHaps_num: 100
minSupportReadsNum_to_hap: 5
interNum_forHap: 10000
minPerct_covered: 0.6
minhapNumNeed_forOut: 1
minDepth_forHapOut: 5
MaxdiffBaseNum_to_MergeReadsHaps: 1
