person: "P22"
CCS_Sample: "P22-C_sL-t"
REF_Sample: "P22-C_sL-d"
software_Path: /home/try/Documents/projects/liuhj-Other/phasing-2024
iSNVtable_P: /home/try/Documents/projects/liuhj-Other/phasing-2024/reliable_locus
refFasta_path: /disk/lhj_4T/lhj/HP/process/assembly/all_genomes
bam_path: /disk/lhj_4T/lhj/HP/process/CCS_map2PersonRespectSamp/ngmlr
OUT_path: /home/try/Documents/projects/liuhj-Other/phasing-2024/haplotype-read




